### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by mcirsta** [Blquinn/repose-qt#1]
Hi. I was looking for a Qt based alternative to Postman and came across your work here. I've found it useful as a starting point and forked it to add some ( in my opinion ) improvements. Could you please add a license to your work ? 
  The less restrictive the better of course but any open source license will do for me.

**Comment by blquinn** [comment]
Sure, I added the MIT license. Go to town :)

**Comment by blquinn** [comment]
I would prefer if you didn't use that name for any software that you decide to release though, especially if it is a rest client because I was planning on using the name.

**Comment by mcirsta** [comment]
Sure, no issues. The name is yours, I'll rename everything. 
Thanks a lot for your work, I think this can be a good alternative to the bloated Postman.

**Comment by blquinn** [comment]
Sounds good, I'll keep an eye on your fork :)
